/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * OpenAPI spec version: LATEST
 *
 * Contact: team@openapitools.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 *
 * https://openapi-generator.tech
 */

// this model was generated using modelData.mustache
package ympa_scala_cask_server.model
import scala.util.control.NonFatal
import scala.util.*

// see https://com-lihaoyi.github.io/upickle/
import upickle.default.{ReadWriter => RW, macroRW}
import upickle.default.*

/** ParcelBoxDTOData a data transfer object, primarily for simple json serialisation.
  * It has no validation - there may be nulls, values out of range, etc
  */
case class ParcelBoxDTOData(
/* {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %}  */
  id: Long = 0 ,

  /* {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %}  */
  fulfilmentId: String = "" 

  ) {

  def asJson: String = write(this)

  def validationErrors(path : Seq[Field], failFast : Boolean) : Seq[ValidationError] = {
    val errors = scala.collection.mutable.ListBuffer[ValidationError]()
        // ==================
        // id






        







        

        // ==================
        // fulfilmentId
        // validate against pattern '^[\\p{Alnum}- ]*$'
        if (errors.isEmpty || !failFast) {
           val regex = """^[\\p{Alnum}- ]*$"""
           if fulfilmentId == null || !regex.r.matches(fulfilmentId) then
              errors += ValidationError(path :+ ParcelBoxDTO.Fields.fulfilmentId, s"value '$fulfilmentId' doesn't match pattern $regex")
        }






        







        

    errors.toSeq
  }

  def validated(failFast : Boolean = false) : scala.util.Try[ParcelBoxDTO] = {
    validationErrors(Vector(), failFast) match {
      case Seq() => Success(asModel)
      case first +: theRest => Failure(ValidationErrors(first, theRest))
    }
  }

  /** use 'validated' to check validation */
  def asModel : ParcelBoxDTO = {
    ParcelBoxDTO(
        id = Option(
        id
        )
        ,
        fulfilmentId = Option(
        fulfilmentId
        )
        
    )
  }
}

object ParcelBoxDTOData {

  given readWriter : RW[ParcelBoxDTOData] = macroRW

  def fromJsonString(jason : String) : ParcelBoxDTOData = try {
        read[ParcelBoxDTOData](jason)
     } catch {
          case NonFatal(e) => sys.error(s"Error parsing json '$jason': $e")
     }

  def manyFromJsonString(jason : String) : Seq[ParcelBoxDTOData] = try {
        read[List[ParcelBoxDTOData]](jason)
    } catch {
        case NonFatal(e) => sys.error(s"Error parsing json '$jason' as list: $e")
    }

  def manyFromJsonStringValidated(jason : String, failFast : Boolean = false) : Try[Seq[ParcelBoxDTO]] = {
      Try(manyFromJsonString(jason)).flatMap { list =>
        list.zipWithIndex.foldLeft(Try(Vector[ParcelBoxDTO]())) {
          case (Success(list), (next, i)) => 
            next.validated(failFast) match {
              case Success(ok) => Success(list :+ ok)
              case Failure(err) => Failure(new Exception(s"Validation error on element $i: ${err.getMessage}", err))
            }
          case (fail, _)  => fail
        }
      }
    }

  def mapFromJsonString(jason : String) : Map[String, ParcelBoxDTOData] = try {
        read[Map[String, ParcelBoxDTOData]](jason)
    } catch {
        case NonFatal(e) => sys.error(s"Error parsing json '$jason' as map: $e")
    }


  def mapFromJsonStringValidated(jason : String, failFast : Boolean = false) : Try[Map[String, ParcelBoxDTO]] = {
     Try(mapFromJsonString(jason)).flatMap { map =>
       map.foldLeft(Try(Map[String, ParcelBoxDTO]())) {
         case (Success(map), (key, next)) =>
           next.validated(failFast) match {
             case Success(ok) => Success(map.updated(key, ok))
             case Failure(err) => Failure(new Exception(s"Validation error on element $key: ${err.getMessage}", err))
           }
         case (fail, _) => fail
       }
     }
  }
}

